import { expect, test } from '@playwright/test'

async function startFirstLevel(page: import('@playwright/test').Page) {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Glassworks' })).toBeVisible()
  await page.getByRole('button', { name: /Enter the Studio|Continue to Map/ }).click()
  await expect(page.getByLabel('Apprentice Studio levels')).toBeVisible()
  const helpDialog = page.getByRole('dialog', { name: 'How to Play' })
  if (await helpDialog.isVisible()) await helpDialog.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: /Build the Line/ }).click()
  await expect(page.getByText('Build Grid')).toBeVisible()
}

test('loads conveyor builder UI', async ({ page }) => {
  await startFirstLevel(page)
  await expect(page.locator('.tool-card').first()).toBeVisible()
  await expect(page.locator('.grid-cell').first()).toBeVisible()
  await expect(page.getByText('Exit →')).toBeVisible()
  await expect(page.getByRole('button', { name: /Run Conveyor/ })).toBeVisible()
  await page.getByRole('button', { name: '?' }).click()
  await expect(page.getByText('Shape Legend')).toBeVisible()
  await expect(page.getByText('╋ Bridge: true crossing —')).toBeVisible()
  await page.getByRole('button', { name: 'Close' }).click()
  await page.screenshot({ path: 'test-results/glassworks-smoke.png', fullPage: true })
})

test('can select a gate colour, place a belt, rotate it, and run on touch', async ({ page }) => {
  await startFirstLevel(page)
  await page.getByRole('button', { name: /Straight/ }).tap()
  await page.locator('.grid-cell.empty').nth(1).tap()
  await expect(page.locator('.grid-cell.piece').first()).toBeVisible()
  await page.locator('.grid-cell.piece').first().tap()
  await expect(page.locator('#edit-count')).toContainText('2 edits')
  await page.getByRole('button', { name: /Run Conveyor/ }).tap()
  await expect(page.locator('#action-banner')).toContainText(/Running .*Amber/)
  await expect(page.locator('.grid-cell.active.color-amber').first()).toBeVisible()
  await expect(page.locator('#run-log')).toContainText(/Amber|No run yet/)
})

test('gate colour picker can choose non-amber gates', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('glassworks-save-v1', JSON.stringify({ version: 1, settings: { defaultSpeed: 'relaxed', sound: true, reducedMotion: false, highContrast: false, loopRelaxed: true, seenIntro: true, seenHelp: true }, completed: { 'apprentice-01': 1, 'apprentice-02': 1 }, results: {} })))
  await page.reload()
  await expect(page.getByLabel('Apprentice Studio levels')).toBeVisible()
  await page.getByRole('button', { name: 'Amber Gate', exact: true }).click()
  await expect(page.getByText('Gate colour')).toBeVisible()
  await page.getByRole('button', { name: /Cobalt gate colour/ }).tap()
  await expect(page.getByRole('button', { name: /Cobalt gate colour/ })).toHaveClass(/selected/)
})

test('blocked tiles and bridge tool appear in later levels', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('glassworks-save-v1', JSON.stringify({ version: 1, settings: { defaultSpeed: 'relaxed', sound: true, reducedMotion: false, highContrast: false, loopRelaxed: true, seenIntro: true, seenHelp: true }, completed: { 'apprentice-01': 1, 'apprentice-02': 1, 'apprentice-03': 1, 'apprentice-04': 1, 'apprentice-05': 1, 'apprentice-06': 1, 'apprentice-07': 1, 'apprentice-08': 1, 'apprentice-09': 1, 'apprentice-10': 1, 'apprentice-11': 1, 'apprentice-12': 1, 'apprentice-13': 1, 'apprentice-14': 1, 'apprentice-15': 1, 'apprentice-16': 1, 'apprentice-17': 1, 'apprentice-18': 1 }, results: {} })))
  await page.reload()
  await expect(page.getByLabel('Apprentice Studio levels')).toBeVisible()
  await page.getByRole('button', { name: /First Bridge/ }).click()
  await expect(page.getByRole('button', { name: /Bridge/ })).toBeVisible()
  await expect(page.locator('.grid-cell.piece').filter({ hasText: '╋' }).first()).toBeVisible()
  await page.getByRole('button', { name: /Map/ }).click()
  await page.getByRole('button', { name: /Vent Maze/ }).click()
  await expect(page.locator('.grid-cell.blocked').first()).toBeVisible()
})

test('continue after solving opens next level directly', async ({ page }) => {
  await startFirstLevel(page)
  await page.getByRole('button', { name: /Straight/ }).tap()
  await page.locator('.grid-cell').nth(6).tap()
  await page.locator('.grid-cell').nth(7).tap()
  await page.locator('.grid-cell').nth(8).tap()
  await page.getByRole('button', { name: /Run Conveyor/ }).tap()
  await expect(page.getByRole('dialog', { name: 'Conveyor Solved' })).toBeVisible({ timeout: 5000 })
  await page.getByRole('button', { name: /Next: First Turn/ }).tap()
  await expect(page.getByRole('heading', { name: 'First Turn' })).toBeVisible()
  await expect(page.getByText('Build Grid')).toBeVisible()
})

test('multi-source bridge level runs both furnaces through one crossing', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => localStorage.setItem('glassworks-save-v1', JSON.stringify({ version: 1, settings: { defaultSpeed: 'relaxed', sound: true, reducedMotion: false, highContrast: false, loopRelaxed: true, seenIntro: true, seenHelp: true }, completed: { 'apprentice-01': 1, 'apprentice-02': 1, 'apprentice-03': 1, 'apprentice-04': 1, 'apprentice-05': 1, 'apprentice-06': 1, 'apprentice-07': 1, 'apprentice-08': 1, 'apprentice-09': 1, 'apprentice-10': 1, 'apprentice-11': 1, 'apprentice-12': 1, 'apprentice-13': 1, 'apprentice-14': 1, 'apprentice-15': 1, 'apprentice-16': 1, 'apprentice-17': 1, 'apprentice-18': 1, 'apprentice-19': 1, 'apprentice-20': 1 }, results: {} })))
  await page.reload()
  await expect(page.getByLabel('Apprentice Studio levels')).toBeVisible()
  await page.getByRole('button', { name: /Twin Furnaces/ }).click()
  await expect(page.getByText('A Exit →')).toBeVisible()
  await expect(page.getByText('B Exit ↑')).toBeVisible()
  await expect(page.locator('.grid-cell.piece').filter({ hasText: '╋' }).first()).toBeVisible()
  await page.getByRole('button', { name: /Straight/ }).tap()
  for (const index of [17, 18, 20, 21, 22, 35, 27, 11]) await page.locator('.grid-cell').nth(index).tap()
  for (const index of [35, 27, 11]) await page.locator('.grid-cell').nth(index).tap()
  await page.getByRole('button', { name: /Run Conveyor/ }).tap()
  await expect(page.locator('#run-log')).toContainText('Furnace A', { timeout: 5000 })
  await expect(page.locator('#run-log')).toContainText('Furnace B')
  await expect(page.getByRole('dialog', { name: 'Conveyor Solved' })).toBeVisible({ timeout: 8000 })
})

test('queued placement assigns pieces and allows placed gate recolor', async ({ page }) => {
  await page.goto('/')
  const completed: Record<string, number> = {}
  for (let i = 1; i <= 25; i++) completed[`apprentice-${String(i).padStart(2, '0')}`] = 1
  await page.evaluate((completed) => localStorage.setItem('glassworks-save-v1', JSON.stringify({ version: 1, settings: { defaultSpeed: 'relaxed', sound: true, reducedMotion: false, highContrast: false, loopRelaxed: true, seenIntro: true, seenHelp: true }, completed, results: {} })), completed)
  await page.reload()
  await expect(page.getByLabel('Apprentice Studio levels')).toBeVisible()
  await page.getByRole('button', { name: /Queued Gate/ }).click()
  await expect(page.getByText('Current Piece')).toBeVisible()
  await expect(page.getByText('Straight', { exact: true })).toBeVisible()
  for (const index of [13, 14, 15, 21, 16]) await page.locator('.grid-cell').nth(index).tap()
  await expect(page.getByText('Queue empty')).toBeVisible()
  await page.locator('.grid-cell').nth(15).tap()
  await expect(page.getByText('Selected gate colour')).toBeVisible()
  await page.getByRole('button', { name: /Cobalt gate colour/ }).tap()
  for (const index of [15, 15, 15, 21]) await page.locator('.grid-cell').nth(index).tap()
  await page.getByRole('button', { name: /Run Conveyor/ }).tap()
  await expect(page.getByRole('dialog', { name: 'Conveyor Solved' })).toBeVisible({ timeout: 8000 })
})
