export const COLORS = {
  amber: { name: 'Amber', hex: '#e6a817', emoji: '🟡' },
  crimson: { name: 'Crimson', hex: '#c04a3d', emoji: '🔴' },
  cobalt: { name: 'Cobalt', hex: '#2c5f8e', emoji: '🔵' },
  emerald: { name: 'Emerald', hex: '#3a7d5c', emoji: '🟢' },
  amethyst: { name: 'Amethyst', hex: '#8b5e9c', emoji: '🟣' },
} as const
export type GlassColor = keyof typeof COLORS
export type Direction = 'N' | 'E' | 'S' | 'W'
export type PieceType = 'straight' | 'corner' | 'gate' | 'bridge'
export type ToolId = PieceType | 'remove'
export type PlacementMode = 'choose' | 'queue'
export type SpeedKey = 'relaxed' | 'normal' | 'fast'
export interface SourceSpec { id?: string; x: number; y: number; dir: Direction; sequence?: GlassColor[] }
export interface KilnSpec { x: number; y: number; color: GlassColor }
export interface Inventory { straight: number; corner: number; gate: number; bridge: number }
export interface FixedPiece { x: number; y: number; type: PieceType; rot: number; color?: GlassColor }
export interface BlockedTile { x: number; y: number }
export interface Level { id: string; studio: 'apprentice'; title: string; subtitle: string; width: number; height: number; source?: SourceSpec; sources?: SourceSpec[]; kilns: KilnSpec[]; sequence?: GlassColor[]; inventory: Inventory; placementMode?: PlacementMode; pieceQueue?: PieceType[]; fixed?: FixedPiece[]; blocked?: BlockedTile[]; targetPieces: number; unlockAfter?: string }
export const SPEEDS: Record<SpeedKey, { label: string; speedMs: number; description: string }> = {
  relaxed: { label: 'Study Run', speedMs: 650, description: 'Slow animation for learning routes.' },
  normal: { label: 'Workshop Run', speedMs: 430, description: 'Standard animation pace.' },
  fast: { label: 'Maestro Run', speedMs: 260, description: 'Fast playback after you know the plan.' },
}
const base = { bridge: 0 }
export const LEVELS: Level[] = [
  { id: 'apprentice-01', studio: 'apprentice', title: 'Build the Line', subtitle: 'Place belts from the furnace to the Amber kiln, then press Run.', width: 5, height: 4, source: { x: 0, y: 1, dir: 'E' }, kilns: [{ x: 4, y: 1, color: 'amber' }], sequence: ['amber', 'amber'], inventory: { straight: 3, corner: 0, gate: 0, ...base }, targetPieces: 3 },
  { id: 'apprentice-02', studio: 'apprentice', title: 'First Turn', subtitle: 'Corners let you bend the cooling track around the bench.', width: 5, height: 5, source: { x: 0, y: 1, dir: 'E' }, kilns: [{ x: 3, y: 4, color: 'amber' }], sequence: ['amber', 'amber', 'amber'], inventory: { straight: 4, corner: 2, gate: 0, ...base }, targetPieces: 5, unlockAfter: 'apprentice-01' },
  { id: 'apprentice-03', studio: 'apprentice', title: 'Amber Gate', subtitle: 'A colour gate sends Amber down and lets everything else continue straight.', width: 6, height: 5, source: { x: 0, y: 2, dir: 'E' }, kilns: [{ x: 5, y: 2, color: 'cobalt' }, { x: 3, y: 4, color: 'amber' }], sequence: ['amber', 'cobalt', 'amber', 'cobalt'], inventory: { straight: 5, corner: 1, gate: 1, ...base }, targetPieces: 5, unlockAfter: 'apprentice-02' },
  { id: 'apprentice-04', studio: 'apprentice', title: 'Shared Trunk', subtitle: 'Build one trunk line, then branch a colour off with the gate.', width: 7, height: 6, source: { x: 0, y: 2, dir: 'E' }, kilns: [{ x: 6, y: 2, color: 'crimson' }, { x: 4, y: 5, color: 'amber' }], sequence: ['crimson', 'amber', 'crimson', 'amber', 'crimson'], inventory: { straight: 6, corner: 2, gate: 1, ...base }, targetPieces: 7, unlockAfter: 'apprentice-03' },
  { id: 'apprentice-05', studio: 'apprentice', title: 'Three Kilns', subtitle: 'A larger board for experimenting with shared paths and branches.', width: 7, height: 6, source: { x: 0, y: 3, dir: 'E' }, kilns: [{ x: 6, y: 3, color: 'cobalt' }, { x: 4, y: 5, color: 'amber' }, { x: 6, y: 1, color: 'crimson' }], sequence: ['amber', 'cobalt', 'crimson', 'amber', 'cobalt'], inventory: { straight: 7, corner: 4, gate: 2, ...base }, targetPieces: 9, unlockAfter: 'apprentice-04' },
  { id: 'apprentice-06', studio: 'apprentice', title: 'North Branch', subtitle: 'A gate can branch a colour upward while the trunk continues forward.', width: 8, height: 6, source: { x: 0, y: 4, dir: 'E' }, kilns: [{ x: 7, y: 4, color: 'cobalt' }, { x: 5, y: 1, color: 'crimson' }, { x: 3, y: 5, color: 'amber' }], sequence: ['crimson', 'cobalt', 'amber', 'crimson', 'cobalt'], inventory: { straight: 8, corner: 4, gate: 2, ...base }, targetPieces: 10, unlockAfter: 'apprentice-05' },
  { id: 'apprentice-07', studio: 'apprentice', title: 'Two Gates, Same Trunk', subtitle: 'Branch two colours from one conveyor trunk before the final colour continues.', width: 8, height: 7, source: { x: 0, y: 3, dir: 'E' }, kilns: [{ x: 7, y: 3, color: 'emerald' }, { x: 4, y: 0, color: 'amber' }, { x: 6, y: 6, color: 'crimson' }], sequence: ['emerald', 'amber', 'crimson', 'emerald', 'crimson', 'amber'], inventory: { straight: 9, corner: 5, gate: 2, ...base }, targetPieces: 12, unlockAfter: 'apprentice-06' },
  { id: 'apprentice-08', studio: 'apprentice', title: 'Turned Trunk', subtitle: 'Route the main trunk around a bend, then split colours after the turn.', width: 8, height: 7, source: { x: 0, y: 1, dir: 'E' }, kilns: [{ x: 7, y: 5, color: 'cobalt' }, { x: 2, y: 6, color: 'amber' }, { x: 7, y: 1, color: 'amethyst' }], sequence: ['amethyst', 'cobalt', 'amber', 'cobalt', 'amethyst', 'amber'], inventory: { straight: 10, corner: 6, gate: 2, ...base }, targetPieces: 13, unlockAfter: 'apprentice-07' },
  { id: 'apprentice-09', studio: 'apprentice', title: 'Five-Colour Feed', subtitle: 'Use four gates so four colours branch away and the last colour rides the trunk.', width: 9, height: 7, source: { x: 0, y: 3, dir: 'E' }, kilns: [{ x: 8, y: 3, color: 'cobalt' }, { x: 5, y: 0, color: 'amber' }, { x: 5, y: 6, color: 'crimson' }, { x: 8, y: 1, color: 'emerald' }, { x: 8, y: 5, color: 'amethyst' }], sequence: ['amber', 'cobalt', 'crimson', 'emerald', 'amethyst', 'cobalt', 'amber'], inventory: { straight: 12, corner: 8, gate: 4, ...base }, targetPieces: 17, unlockAfter: 'apprentice-08' },
  { id: 'apprentice-10', studio: 'apprentice', title: 'Apprentice Switchyard', subtitle: 'A full routing challenge with several branches and limited parts.', width: 9, height: 8, source: { x: 0, y: 4, dir: 'E' }, kilns: [{ x: 8, y: 4, color: 'cobalt' }, { x: 4, y: 0, color: 'amber' }, { x: 6, y: 7, color: 'crimson' }, { x: 8, y: 1, color: 'emerald' }, { x: 2, y: 7, color: 'amethyst' }], sequence: ['cobalt', 'amber', 'crimson', 'emerald', 'amethyst', 'amber', 'cobalt', 'crimson'], inventory: { straight: 13, corner: 8, gate: 4, ...base }, targetPieces: 18, unlockAfter: 'apprentice-09' },
  { id: 'apprentice-11', studio: 'apprentice', title: 'Fixed Starter', subtitle: 'Some belts are already installed; complete the machine around them.', width: 7, height: 5, source: { x: 0, y: 2, dir: 'E' }, kilns: [{ x: 6, y: 2, color: 'cobalt' }, { x: 4, y: 4, color: 'amber' }], sequence: ['amber', 'cobalt', 'amber'], inventory: { straight: 4, corner: 2, gate: 1, ...base }, fixed: [{ x: 1, y: 2, type: 'straight', rot: 0 }], targetPieces: 6, unlockAfter: 'apprentice-10' },
  { id: 'apprentice-12', studio: 'apprentice', title: 'Locked Bend', subtitle: 'A fixed corner forces the trunk to turn before you branch.', width: 7, height: 6, source: { x: 0, y: 1, dir: 'E' }, kilns: [{ x: 5, y: 5, color: 'cobalt' }, { x: 6, y: 1, color: 'crimson' }], sequence: ['crimson', 'cobalt', 'crimson'], inventory: { straight: 6, corner: 3, gate: 1, ...base }, fixed: [{ x: 3, y: 1, type: 'corner', rot: 1 }], targetPieces: 8, unlockAfter: 'apprentice-11' },
  { id: 'apprentice-13', studio: 'apprentice', title: 'Hot Tiles', subtitle: 'Furnace vents block part of the bench; route around them.', width: 8, height: 6, source: { x: 0, y: 3, dir: 'E' }, kilns: [{ x: 7, y: 3, color: 'cobalt' }, { x: 5, y: 0, color: 'amber' }], sequence: ['amber', 'cobalt', 'amber'], inventory: { straight: 8, corner: 4, gate: 1, ...base }, blocked: [{ x: 3, y: 2 }, { x: 3, y: 3 }, { x: 3, y: 4 }], targetPieces: 10, unlockAfter: 'apprentice-12' },
  { id: 'apprentice-14', studio: 'apprentice', title: 'Vent Maze', subtitle: 'Blocked cells make the shortest-looking path impossible.', width: 8, height: 7, source: { x: 0, y: 5, dir: 'E' }, kilns: [{ x: 7, y: 5, color: 'emerald' }, { x: 6, y: 1, color: 'crimson' }, { x: 2, y: 0, color: 'amber' }], sequence: ['emerald', 'crimson', 'amber', 'emerald'], inventory: { straight: 10, corner: 6, gate: 2, ...base }, blocked: [{ x: 2, y: 4 }, { x: 3, y: 4 }, { x: 4, y: 4 }, { x: 4, y: 3 }], targetPieces: 13, unlockAfter: 'apprentice-13' },
  { id: 'apprentice-15', studio: 'apprentice', title: 'Fixed Amber Gate', subtitle: 'The gate is installed; choose how to connect its branch and trunk.', width: 8, height: 6, source: { x: 0, y: 2, dir: 'E' }, kilns: [{ x: 7, y: 2, color: 'cobalt' }, { x: 4, y: 5, color: 'amber' }], sequence: ['amber', 'cobalt', 'amber', 'cobalt'], inventory: { straight: 6, corner: 3, gate: 0, ...base }, fixed: [{ x: 3, y: 2, type: 'gate', rot: 0, color: 'amber' }], targetPieces: 8, unlockAfter: 'apprentice-14' },
  { id: 'apprentice-16', studio: 'apprentice', title: 'Fixed Crimson Gate', subtitle: 'A fixed upward crimson branch changes where the trunk can go.', width: 8, height: 6, source: { x: 0, y: 4, dir: 'E' }, kilns: [{ x: 7, y: 4, color: 'cobalt' }, { x: 5, y: 1, color: 'crimson' }], sequence: ['cobalt', 'crimson', 'cobalt'], inventory: { straight: 6, corner: 3, gate: 0, ...base }, fixed: [{ x: 3, y: 4, type: 'gate', rot: 2, color: 'crimson' }], targetPieces: 8, unlockAfter: 'apprentice-15' },
  { id: 'apprentice-17', studio: 'apprentice', title: 'Barely Enough', subtitle: 'Inventory is tight; every piece must serve the shared route.', width: 8, height: 6, source: { x: 0, y: 3, dir: 'E' }, kilns: [{ x: 7, y: 3, color: 'cobalt' }, { x: 4, y: 5, color: 'amber' }, { x: 6, y: 1, color: 'crimson' }], sequence: ['amber', 'cobalt', 'crimson', 'cobalt'], inventory: { straight: 6, corner: 2, gate: 2, ...base }, targetPieces: 8, unlockAfter: 'apprentice-16' },
  { id: 'apprentice-18', studio: 'apprentice', title: 'No Spare Corners', subtitle: 'A wide layout with too few corners rewards a clean trunk.', width: 9, height: 6, source: { x: 0, y: 2, dir: 'E' }, kilns: [{ x: 8, y: 2, color: 'emerald' }, { x: 6, y: 5, color: 'amber' }, { x: 8, y: 0, color: 'crimson' }], sequence: ['emerald', 'amber', 'crimson', 'emerald'], inventory: { straight: 9, corner: 2, gate: 2, ...base }, targetPieces: 10, unlockAfter: 'apprentice-17' },
  { id: 'apprentice-19', studio: 'apprentice', title: 'First Bridge', subtitle: 'The fixed bridge is the crossing point: the trunk passes through while branches cross vertically.', width: 7, height: 7, source: { x: 0, y: 3, dir: 'E' }, kilns: [{ x: 6, y: 3, color: 'cobalt' }, { x: 3, y: 0, color: 'amber' }, { x: 3, y: 6, color: 'crimson' }], sequence: ['amber', 'cobalt', 'crimson', 'cobalt'], inventory: { straight: 8, corner: 4, gate: 2, bridge: 0 }, fixed: [{ x: 3, y: 3, type: 'bridge', rot: 0 }], targetPieces: 10, unlockAfter: 'apprentice-18' },
  { id: 'apprentice-20', studio: 'apprentice', title: 'Bridge Switchyard', subtitle: 'Use bridges and gates together to pack more routes into less space.', width: 9, height: 8, source: { x: 0, y: 4, dir: 'E' }, kilns: [{ x: 8, y: 4, color: 'cobalt' }, { x: 4, y: 0, color: 'amber' }, { x: 4, y: 7, color: 'crimson' }, { x: 8, y: 1, color: 'emerald' }], sequence: ['amber', 'cobalt', 'crimson', 'emerald', 'cobalt', 'amber'], inventory: { straight: 12, corner: 6, gate: 3, bridge: 2 }, targetPieces: 16, unlockAfter: 'apprentice-19' },
  { id: 'apprentice-21', studio: 'apprentice', title: 'Twin Furnaces', subtitle: 'Two sources cross at a fixed bridge: solve both streams with one machine.', width: 8, height: 6, sources: [{ id: 'A', x: 0, y: 2, dir: 'E', sequence: ['amber', 'amber'] }, { id: 'B', x: 3, y: 5, dir: 'N', sequence: ['cobalt', 'cobalt'] }], kilns: [{ x: 7, y: 2, color: 'amber' }, { x: 3, y: 0, color: 'cobalt' }], sequence: [], inventory: { straight: 8, corner: 0, gate: 0, bridge: 0 }, fixed: [{ x: 3, y: 2, type: 'bridge', rot: 0 }], targetPieces: 8, unlockAfter: 'apprentice-20' },
  { id: 'apprentice-22', studio: 'apprentice', title: 'Placed Overpass', subtitle: 'This time you place the bridge where two furnace routes cross.', width: 8, height: 6, sources: [{ id: 'A', x: 0, y: 3, dir: 'E', sequence: ['amber', 'amber'] }, { id: 'B', x: 4, y: 5, dir: 'N', sequence: ['crimson', 'crimson'] }], kilns: [{ x: 7, y: 3, color: 'amber' }, { x: 4, y: 0, color: 'crimson' }], sequence: [], inventory: { straight: 7, corner: 2, gate: 0, bridge: 1 }, targetPieces: 8, unlockAfter: 'apprentice-21' },
  { id: 'apprentice-23', studio: 'apprentice', title: 'Crossed Branches', subtitle: 'Two furnaces, one shared crossing, and a gate branch on the main line.', width: 9, height: 7, sources: [{ id: 'A', x: 0, y: 3, dir: 'E', sequence: ['cobalt', 'amber', 'cobalt'] }, { id: 'B', x: 4, y: 6, dir: 'N', sequence: ['crimson', 'crimson'] }], kilns: [{ x: 8, y: 3, color: 'cobalt' }, { x: 5, y: 0, color: 'crimson' }, { x: 6, y: 6, color: 'amber' }], sequence: [], inventory: { straight: 11, corner: 4, gate: 1, bridge: 1 }, targetPieces: 13, unlockAfter: 'apprentice-22' },
  { id: 'apprentice-24', studio: 'apprentice', title: 'Queued Line', subtitle: 'Place the fixed draw queue in order; the next piece is chosen for you.', width: 5, height: 4, source: { x: 0, y: 1, dir: 'E' }, kilns: [{ x: 4, y: 1, color: 'amber' }], sequence: ['amber', 'amber'], inventory: { straight: 3, corner: 0, gate: 0, bridge: 0 }, placementMode: 'queue', pieceQueue: ['straight', 'straight', 'straight'], targetPieces: 3, unlockAfter: 'apprentice-23' },
  { id: 'apprentice-25', studio: 'apprentice', title: 'Queued Bend', subtitle: 'The queue includes one corner; place it where the path must turn, then rotate it.', width: 5, height: 5, source: { x: 0, y: 1, dir: 'E' }, kilns: [{ x: 3, y: 4, color: 'amber' }], sequence: ['amber', 'amber'], inventory: { straight: 4, corner: 1, gate: 0, bridge: 0 }, placementMode: 'queue', pieceQueue: ['straight', 'straight', 'corner', 'straight', 'straight'], targetPieces: 5, unlockAfter: 'apprentice-24' },
  { id: 'apprentice-26', studio: 'apprentice', title: 'Queued Gate', subtitle: 'Place the gate from the queue, then configure its colour and arrow after it lands.', width: 6, height: 5, source: { x: 0, y: 2, dir: 'E' }, kilns: [{ x: 5, y: 2, color: 'amber' }, { x: 3, y: 4, color: 'cobalt' }], sequence: ['cobalt', 'amber', 'cobalt'], inventory: { straight: 4, corner: 0, gate: 1, bridge: 0 }, placementMode: 'queue', pieceQueue: ['straight', 'straight', 'gate', 'straight', 'straight'], targetPieces: 5, unlockAfter: 'apprentice-25' },
]

export function unlockedLevelIds(completed: Record<string, number>): Set<string> { const ids = new Set<string>(); for (const level of LEVELS) if (!level.unlockAfter || completed[level.unlockAfter]) ids.add(level.id); return ids }
