import './styles.css'
import { AudioManager } from './audio'
import { COLORS, LEVELS, SPEEDS, type Direction, type GlassColor, type Level, type PieceType, type SpeedKey, type ToolId, unlockedLevelIds } from './levels'
import { loadSave, resetProgress, saveGame, type SaveData } from './storage'

type Screen = 'intro' | 'map' | 'game'
type PlacedPiece = { type: PieceType; rot: number; color?: GlassColor; fixed?: boolean }
type RunStep = { color: GlassColor; ok: boolean; message: string; path: string[] }
type GameState = { level: Level; speed: SpeedKey; pieces: Record<string, PlacedPiece>; selectedTool: ToolId; edits: number; attempts: number; running: boolean; cursorPath: string[]; run: RunStep[]; ended: false | 'won' }
const audio = new AudioManager(); let save: SaveData = loadSave(); let screen: Screen = save.settings.seenIntro ? 'map' : 'intro'; let state: GameState | null = null; let runTimer = 0; const app = document.querySelector<HTMLDivElement>('#app')!
const dirs: Record<Direction, [number, number]> = { N: [0, -1], E: [1, 0], S: [0, 1], W: [-1, 0] }; const opposite: Record<Direction, Direction> = { N: 'S', E: 'W', S: 'N', W: 'E' }
function h<K extends keyof HTMLElementTagNameMap>(tag: K, className = '', text = ''): HTMLElementTagNameMap[K] { const el = document.createElement(tag); if (className) el.className = className; if (text) el.textContent = text; return el }
function key(x: number, y: number): string { return `${x},${y}` }
function route(next: Screen): void { screen = next; render() }
function render(): void { document.body.classList.toggle('reduced-motion', save.settings.reducedMotion); document.body.classList.toggle('high-contrast', save.settings.highContrast); audio.setEnabled(save.settings.sound); if (screen === 'intro') renderIntro(); if (screen === 'map') renderMap(); if (screen === 'game') renderGameShell() }
function renderIntro(): void { stopRun(); app.innerHTML = `<div id="live-region" class="sr-only" aria-live="polite"></div>`; const wrap = h('main', 'screen intro-screen'); wrap.innerHTML = `<section class="intro-card"><div class="furnace-mark">🔥</div><h1>Glassworks</h1><p class="subtitle">Conveyor Builder Prototype</p><p>Build the belt. Place straight tracks, corners, and colour gates between the furnace and kilns.</p><p>Press Run Conveyor to watch each molten globe travel through the machine you designed.</p><button class="primary" id="enter-studio">Enter the Studio</button></section>`; app.append(wrap); document.querySelector('#enter-studio')?.addEventListener('click', () => { save.settings.seenIntro = true; saveGame(save); audio.play('tap'); route('map') }) }
function renderMap(): void { stopRun(); state = null; app.innerHTML = `<div id="live-region" class="sr-only" aria-live="polite"></div>`; const unlocked = unlockedLevelIds(save.completed), totalStars = Object.values(save.results).reduce((sum, result) => sum + result.stars, 0), wrap = h('main', 'screen map-screen'); wrap.innerHTML = `<header class="map-hero"><div><p class="eyebrow">Murano Conveyor Lab</p><h1>Glassworks</h1><p>Build conveyor belts, route colour gates, and test the machine.</p></div><div class="hero-actions"><button class="ghost" id="settings-open">⚙ Settings</button><button class="ghost" id="help-open">? Help</button></div></header><section class="progress-panel"><span>${Object.keys(save.completed).length}/${LEVELS.length} conveyors solved</span><span>${totalStars}★ earned</span><span>Playback: ${SPEEDS[save.settings.defaultSpeed].label}</span></section><section class="level-grid" aria-label="Apprentice Studio levels"></section>`; const grid = wrap.querySelector('.level-grid')!; for (const level of LEVELS) { const isUnlocked = unlocked.has(level.id), result = save.results[level.id], button = h('button', `level-card ${isUnlocked ? '' : 'locked'}`); button.disabled = !isUnlocked; button.setAttribute('aria-label', `${level.title} ${isUnlocked ? '' : 'locked'}`); button.innerHTML = `<span class="level-num">${level.id.split('-')[1]}</span><strong>${level.title}</strong><span>${level.subtitle}</span><span class="stars">${result ? '★'.repeat(result.stars) + '☆'.repeat(3 - result.stars) : '☆☆☆'}</span>`; button.addEventListener('click', () => startLevel(level, save.settings.defaultSpeed)); grid.append(button) } app.append(wrap); document.querySelector('#help-open')?.addEventListener('click', showHelp); document.querySelector('#settings-open')?.addEventListener('click', showSettings); if (!save.settings.seenHelp) showHelp() }
function showHelp(): void { save.settings.seenHelp = true; saveGame(save); showModal('How to Play', `<ol class="help-list"><li><strong>Build the belt.</strong> Select a tool, then tap grid cells to place pieces.</li><li><strong>Rotate pieces.</strong> Tap a placed belt to rotate it.</li><li><strong>Use gates.</strong> The Amber Gate sends Amber through its branch and lets other colours continue straight.</li><li><strong>Press Run.</strong> Watch globes travel. The log tells you where they succeeded or failed.</li><li><strong>Win by delivering every globe to its matching kiln.</strong></li></ol>`) }
function showSettings(): void { showModal('Settings', `<label class="setting-row">Playback speed<select id="setting-speed">${Object.entries(SPEEDS).map(([key, speed]) => `<option value="${key}" ${save.settings.defaultSpeed === key ? 'selected' : ''}>${speed.label}</option>`).join('')}</select></label><label class="setting-row"><input id="setting-sound" type="checkbox" ${save.settings.sound ? 'checked' : ''}> Sound effects</label><label class="setting-row"><input id="setting-reduced" type="checkbox" ${save.settings.reducedMotion ? 'checked' : ''}> Reduced motion</label><label class="setting-row"><input id="setting-contrast" type="checkbox" ${save.settings.highContrast ? 'checked' : ''}> High-contrast patterns</label><button class="danger wide" id="reset-progress">Reset all progress</button>`); const speed = document.querySelector<HTMLSelectElement>('#setting-speed')!, sound = document.querySelector<HTMLInputElement>('#setting-sound')!, reduced = document.querySelector<HTMLInputElement>('#setting-reduced')!, contrast = document.querySelector<HTMLInputElement>('#setting-contrast')!; const persist = () => { save.settings.defaultSpeed = speed.value as SpeedKey; save.settings.sound = sound.checked; save.settings.reducedMotion = reduced.checked; save.settings.highContrast = contrast.checked; saveGame(save); render(); showSettings() }; [speed, sound, reduced, contrast].forEach((input) => input.addEventListener('change', persist)); document.querySelector('#reset-progress')?.addEventListener('click', () => { save = resetProgress(save); saveGame(save); closeModal(); route('map') }) }
function showModal(title: string, body: string): void { closeModal(); const overlay = h('div', 'modal-backdrop'); overlay.innerHTML = `<section class="modal" role="dialog" aria-modal="true" aria-label="${title}"><button class="modal-close" aria-label="Close">×</button><h2>${title}</h2>${body}</section>`; document.body.append(overlay); overlay.querySelector('.modal-close')?.addEventListener('click', closeModal) } function closeModal(): void { document.querySelector('.modal-backdrop')?.remove() }
function startLevel(level: Level, speed: SpeedKey): void { closeModal(); stopRun(); const pieces: Record<string, PlacedPiece> = {}; for (const fixed of level.fixed ?? []) pieces[key(fixed.x, fixed.y)] = { type: fixed.type, rot: fixed.rot, color: fixed.color, fixed: true }; state = { level, speed, pieces, selectedTool: level.inventory.straight > 0 ? 'straight' : 'corner', edits: 0, attempts: 0, running: false, cursorPath: [], run: [], ended: false }; screen = 'game'; render() }
function renderGameShell(): void { if (!state) return; const level = state.level, speed = SPEEDS[state.speed], wrap = h('main', 'screen game-screen'); app.innerHTML = `<div id="live-region" class="sr-only" aria-live="polite"></div>`; wrap.innerHTML = `<header class="game-topbar"><button class="ghost" id="back-map">← Map</button><div><p class="eyebrow">${speed.label}</p><h1>${level.title}</h1></div><div class="statline"><span id="attempt-count">0 runs</span><span id="edit-count">0 edits</span><span id="star-meter">☆☆☆</span></div><button class="ghost" id="game-settings">⚙</button><button class="ghost" id="game-help">?</button></header><section class="game-board builder-board"><div class="action-banner" id="action-banner">Select a belt piece, place it on the grid, rotate pieces, then Run Conveyor.</div><section class="tool-panel"><div class="panel-title">Piece Tray <small>limited parts</small></div><div id="tool-list"></div><button class="primary wide" id="run-btn">▶ Run Conveyor</button><button class="ghost wide" id="reset-build">Reset Build</button></section><section class="grid-panel"><div class="panel-title">Build Grid <small>tap placed pieces to rotate</small></div><div class="build-grid" id="build-grid"></div></section><section class="route-panel"><div class="panel-title">Run Log <small>delivery feedback</small></div><div id="run-log"><p>No run yet.</p></div></section></section>`; app.append(wrap); document.querySelector('#back-map')?.addEventListener('click', () => route('map')); document.querySelector('#game-help')?.addEventListener('click', showHelp); document.querySelector('#game-settings')?.addEventListener('click', showSettings); document.querySelector('#run-btn')?.addEventListener('click', runConveyor); document.querySelector('#reset-build')?.addEventListener('click', () => startLevel(state!.level, state!.speed)); renderGameState() }
function renderGameState(): void { if (!state) return; renderTools(); renderGrid(); document.querySelector('#attempt-count')!.textContent = `${state.attempts} runs`; document.querySelector('#edit-count')!.textContent = `${state.edits} edits`; document.querySelector('#star-meter')!.textContent = '★'.repeat(calculateStars(state)) + '☆'.repeat(3 - calculateStars(state)); const log = document.querySelector('#run-log')!; log.innerHTML = state.run.length ? state.run.map((step) => `<div class="log-row ${step.ok ? 'ok' : 'bad'}">${COLORS[step.color].emoji} ${COLORS[step.color].name}: ${step.message}</div>`).join('') : '<p>No run yet.</p>' }
function renderTools(): void { if (!state) return; const used = countUsed(), inv = state.level.inventory, tools: ToolId[] = ['straight', 'corner', 'gate', 'remove']; document.querySelector('#tool-list')!.innerHTML = tools.map((tool) => { const remaining = tool === 'remove' ? '∞' : String(inv[tool] - used[tool]); const label = tool === 'straight' ? 'Straight' : tool === 'corner' ? 'Corner' : tool === 'gate' ? 'Amber Gate' : 'Remove'; return `<button class="tool-card ${state!.selectedTool === tool ? 'selected' : ''}" data-tool="${tool}" aria-label="${label}"><strong>${label}</strong><span>${remaining}</span></button>` }).join(''); document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach((button) => button.addEventListener('click', () => { state!.selectedTool = button.dataset.tool as ToolId; renderGameState() })) }
function renderGrid(): void { if (!state) return; const grid = document.querySelector('#build-grid') as HTMLElement; grid.innerHTML = ''; grid.style.gridTemplateColumns = `repeat(${state.level.width}, minmax(44px, 1fr))`; for (let y = 0; y < state.level.height; y++) for (let x = 0; x < state.level.width; x++) { const k = key(x, y), piece = state.pieces[k], kiln = state.level.kilns.find((item) => item.x === x && item.y === y), isSource = state.level.source.x === x && state.level.source.y === y, active = state.cursorPath.includes(k), cell = h('button', `grid-cell ${piece ? 'piece' : 'empty'} ${kiln ? `kiln color-${kiln.color}` : ''} ${isSource ? 'source' : ''} ${active ? 'active' : ''}`); cell.setAttribute('aria-label', cellLabel(x, y, piece)); cell.innerHTML = cellContents(x, y, piece); cell.addEventListener('click', () => clickCell(x, y)); grid.append(cell) } }
function cellLabel(x: number, y: number, piece?: PlacedPiece): string { const kiln = state?.level.kilns.find((item) => item.x === x && item.y === y); if (kiln) return `${COLORS[kiln.color].name} kiln`; if (state?.level.source.x === x && state.level.source.y === y) return 'Furnace source'; return piece ? `${piece.type} belt` : 'empty build cell' }
function cellContents(x: number, y: number, piece?: PlacedPiece): string { const kiln = state?.level.kilns.find((item) => item.x === x && item.y === y); if (kiln) return `<span>${COLORS[kiln.color].emoji}</span><small>Kiln</small>`; if (state?.level.source.x === x && state.level.source.y === y) return '<span>🔥</span><small>Start</small>'; if (!piece) return ''; const icon = piece.type === 'straight' ? (piece.rot % 2 === 0 ? '━' : '┃') : piece.type === 'corner' ? ['┗','┏','┓','┛'][piece.rot % 4] : `🟡${['↳','↱','↰','↲'][piece.rot % 4]}`; return `<span>${icon}</span>` }
function clickCell(x: number, y: number): void { if (!state || state.running) return; const k = key(x, y); if (state.level.kilns.some((item) => item.x === x && item.y === y) || (state.level.source.x === x && state.level.source.y === y)) return; const piece = state.pieces[k]; if (state.selectedTool === 'remove') { if (piece && !piece.fixed) { delete state.pieces[k]; state.edits++; audio.play('tap') } renderGameState(); return } if (piece) { if (!piece.fixed) { piece.rot = (piece.rot + 1) % 4; state.edits++; audio.play('tap') } renderGameState(); return } const used = countUsed(); if (used[state.selectedTool] >= state.level.inventory[state.selectedTool]) return; state.pieces[k] = { type: state.selectedTool, rot: 0, color: state.selectedTool === 'gate' ? 'amber' : undefined }; state.edits++; audio.play('tap'); renderGameState() }
function countUsed(): Record<PieceType, number> { const out = { straight: 0, corner: 0, gate: 0 }; if (!state) return out; for (const piece of Object.values(state.pieces)) if (!piece.fixed) out[piece.type]++; return out }
function exits(piece: PlacedPiece, color: GlassColor, incoming: Direction): Direction | null { if (piece.type === 'straight') { const pair: Direction[] = piece.rot % 2 === 0 ? ['E','W'] : ['N','S']; return pair.includes(incoming) ? opposite[incoming] : null } if (piece.type === 'corner') { const pairs: [Direction, Direction][] = [['N','E'],['E','S'],['S','W'],['W','N']]; const pair = pairs[piece.rot % 4]; return pair.includes(incoming) ? pair.find((d) => d !== incoming)! : null } const straight: Direction[] = piece.rot % 2 === 0 ? ['E','W'] : ['N','S']; if (color !== piece.color) return straight.includes(incoming) ? opposite[incoming] : null; return ['S','W','N','E'][piece.rot % 4] as Direction }
function runConveyor(): void { if (!state || state.running) return; stopRun(); state.attempts++; state.run = []; state.cursorPath = []; state.running = true; const steps = [...state.level.sequence]; let i = 0; const next = () => { if (!state) return; if (i >= steps.length) { finishRun(); return } const result = simulate(steps[i]); state.run.push(result); state.cursorPath = result.path; audio.play(result.ok ? 'place' : 'shatter'); renderGameState(); i++; runTimer = window.setTimeout(next, SPEEDS[state.speed].speedMs) }; next() }
function simulate(color: GlassColor): RunStep { if (!state) return { color, ok: false, message: 'No state', path: [] }; let x = state.level.source.x, y = state.level.source.y, dir = state.level.source.dir; const path: string[] = []; for (let step = 0; step < 50; step++) { x += dirs[dir][0]; y += dirs[dir][1]; const k = key(x, y); path.push(k); const kiln = state.level.kilns.find((item) => item.x === x && item.y === y); if (kiln) return { color, ok: kiln.color === color, message: kiln.color === color ? `Delivered to ${COLORS[kiln.color].name} kiln` : `Wrong kiln: reached ${COLORS[kiln.color].name}`, path }; const piece = state.pieces[k]; if (!piece) return { color, ok: false, message: 'Track ended before a kiln', path }; const out = exits(piece, color, opposite[dir]); if (!out) return { color, ok: false, message: 'Belt piece does not connect', path }; dir = out } return { color, ok: false, message: 'Loop detected', path } }
function finishRun(): void { if (!state) return; state.running = false; state.cursorPath = []; renderGameState(); if (state.run.every((step) => step.ok)) endLevel() }
function stopRun(): void { if (runTimer) window.clearTimeout(runTimer); runTimer = 0 }
function nextLevelAfter(levelId: string): Level | null { const index = LEVELS.findIndex((level) => level.id === levelId); return index >= 0 ? LEVELS[index + 1] ?? null : null }
function endLevel(): void { if (!state || state.ended) return; state.ended = 'won'; const completedLevelId = state.level.id, nextLevel = nextLevelAfter(completedLevelId), stars = calculateStars(state), existing = save.results[completedLevelId]; save.completed[completedLevelId] = Math.max(save.completed[completedLevelId] ?? 0, stars); save.results[completedLevelId] = { stars: Math.max(existing?.stars ?? 0, stars), bestTime: existing ? Math.min(existing.bestTime, state.attempts) : state.attempts, bestCullet: existing ? Math.min(existing.bestCullet, state.edits) : state.edits }; saveGame(save); audio.play('win'); showModal('Conveyor Solved', `<p class="modal-copy">Every globe reached the correct kiln.</p><div class="victory-stars">${'★'.repeat(stars)}${'☆'.repeat(3 - stars)}</div><p>Runs: ${state.attempts} · Edits: ${state.edits}</p><button class="primary wide" id="next-action">${nextLevel ? `Next: ${nextLevel.title}` : 'Back to Map'}</button><button class="ghost wide" id="map-action">Map</button>`); document.querySelector('#next-action')?.addEventListener('click', () => { closeModal(); if (nextLevel) startLevel(nextLevel, save.settings.defaultSpeed); else route('map') }); document.querySelector('#map-action')?.addEventListener('click', () => { closeModal(); route('map') }) }
function calculateStars(game: GameState): number { if (!game.run.length || !game.run.every((step) => step.ok)) return 1; const used = Object.values(countUsed()).reduce((a, b) => a + b, 0); if (used <= game.level.targetPieces && game.attempts <= 2) return 3; if (used <= game.level.targetPieces + 2) return 2; return 1 }
window.addEventListener('pointerdown', () => void audio.unlock(), { once: true })
render()
